image:
  file: .gitpod.Dockerfile

tasks:
  - name: Running docker-compose
    command: >
      docker-compose up -d
      && gp sync-done running-docker-compose

jetbrains:
  intellij:
    plugins:
      - org.intellij.scala
      - com.intellij.play
      - com.github.tomasmilata.intelliroutes
    prebuilds:
      version: stable
