image:
  file: .gitpod/base.Dockerfile

tasks:
  - name: Running docker-compose
    command: >
      docker-compose up -d
      && gp sync-done running-docker-compose

  - name: run cfp (with play2)
    init: gp sync-await running-docker-compose
    command: |
      ./.gitpod/run.sh

jetbrains:
  intellij:
    plugins:
      - org.intellij.scala
      - com.intellij.play
      - com.github.tomasmilata.intelliroutes
    prebuilds:
      version: stable
