/*
 * The MIT License (MIT)
 *
 * Copyright (c) 2013 Association du Paris Java User Group.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of
 * this software and associated documentation files (the "Software"), to deal in
 * the Software without restriction, including without limitation the rights to
 * use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
 * the Software, and to permit persons to whom the Software is furnished to do so,
 * subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
 * FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
 * COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
 * IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

package models

import play.api.test.{WithApplication, FakeApplication, PlaySpecification}

/**
 * Play uses Specs2 for testing.
 *
 * Author: nicolas
 * Created: 14/01/2014 12:17
 */
class ProposalSpecs extends PlaySpecification {
  // Test with a remote server to check for performance issues
  val remoteRedisTestServer = Map(
    "redis.host" -> "localhost"
    , "redis.port" -> "6364"
    //,"redis.password" -> "test_540240240230423042440230"
  )
  val appWithTestRedis = FakeApplication(additionalConfiguration = remoteRedisTestServer)

  "correctly update the track when we change one proposal track to another" in new WithApplication(appWithTestRedis) {

    val newProposal = new Proposal(id="TST-000", "DV", "fr", "title","1234",
                                  None,Nil,
                                  ProposalType.CONF, "audience",
                                  "summary","generated by tests",
                                  ProposalState.UNKNOWN, sponsorTalk = false,
                                  Track.JAVA, "d1",
                                  userGroup = false,
                                  wishlisted = Some(false))

    Proposal.save("123", newProposal, ProposalState.SUBMITTED)

    val Some(proposal) = Proposal.findById("TST-000")
    proposal.id must equalTo("TST-000")
    proposal.track must equalTo(Track.JAVA)
    proposal.state must equalTo(ProposalState.SUBMITTED)

    // Get total of votes for JAVA
    val totalSubmitted = Proposal.totalSubmittedByTrack()
    val totalJava = totalSubmitted.find(p=>p._1==Track.JAVA)
    val totalFuture = totalSubmitted.find(p=>p._1==Track.FUTURE)
    val totalJavaDepart = totalJava.map(_._2).getOrElse(0)
    val totalFutureDepart = totalFuture.map(_._2).getOrElse(0)

    Proposal.changeTrack("1234", proposal.copy(track = Track.FUTURE))
    val totalSubmitted2 = Proposal.totalSubmittedByTrack()
    val totalJava2 = totalSubmitted2.find(p=>p._1==Track.JAVA)
    val totalFuture2 = totalSubmitted2.find(p=>p._1==Track.FUTURE)
    totalJava2.map(_._2).getOrElse(0) must equalTo(totalJavaDepart - 1)
    totalFuture2.map(_._2).getOrElse(0) must equalTo(totalFutureDepart +1)

    Proposal.changeTrack("1234", proposal.copy(track = Track.FUTURE))
    val totalSubmitted3 = Proposal.totalSubmittedByTrack()
    val totalJava3 = totalSubmitted3.find(p=>p._1==Track.JAVA)
    val totalFuture3 = totalSubmitted3.find(p=>p._1==Track.FUTURE)
    totalJava3.map(_._2).getOrElse(0) must equalTo(totalJavaDepart - 1)
    totalFuture3.map(_._2).getOrElse(0) must equalTo(totalFutureDepart +1)

    Proposal.changeTrack("1234", proposal.copy(track = Track.JAVA))
    val totalSubmitted4 = Proposal.totalSubmittedByTrack()
    val totalJavaFinal = totalSubmitted4.find(p=>p._1==Track.JAVA)
    val totalFuture4 = totalSubmitted4.find(p=>p._1==Track.FUTURE)
    totalJavaFinal.map(_._2).getOrElse(0) must equalTo(totalJavaDepart)
    totalFuture4.map(_._2).getOrElse(0) must equalTo(totalFutureDepart)

    Proposal.delete("1234","TST-000")
  }
}
